"""Build the independent content document; standard library only."""
from pathlib import Path
import argparse
ROOT = Path(__file__).resolve().parents[1]
def build():
    parts = ['<!-- Generated by scripts/build_bundle.py. Edit rules/. -->',
             (ROOT/'rules/START.md').read_text(), 'Package version: '+(ROOT/'VERSION').read_text().strip(),
             (ROOT/'rules/copy.md').read_text(), (ROOT/'rules/examples.md').read_text(),
             (ROOT/'NOTICE.md').read_text(), '# Apache-2.0 license\n\n```text\n'+(ROOT/'LICENSE').read_text()+'\n```']
    for p in sorted((ROOT/'licenses').glob('*.txt')):
        parts.append('# MIT notice: '+p.stem+'\n\n```text\n'+p.read_text()+'\n```')
    return '\n\n'.join(p.strip() for p in parts)+'\n'
def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    path=ROOT/'CONTENT-RULES.md'; expected=build()
    if args.check:
        if not path.exists() or path.read_text()!=expected: parser.exit(1,'CONTENT-RULES.md is missing or stale.\n')
    else: path.write_text(expected)
    print('Content bundle is current.')
if __name__=='__main__': main()
